# Project 2

## Hypothesis
### Years with more fire-related emergency incidents reported to OEM will also show more confirmed fires in FDNY’s Bureau of Fire Investigations dataset, reflecting consistent trends across the two systems.

In [3]:
import pandas as pd

oem = pd.read_csv("Emergency_Response.csv")
bfi = pd.read_csv("Bureau_of_Fire_Investigations.csv")

### Data cleaning for Emergency_Response

In [4]:
fire_oem = oem[oem["Incident Type"].str.contains("FIRE", case=False, na=False)]

fire_oem["Creation Date"] = pd.to_datetime(fire_oem["Creation Date"])
fire_oem["year"] = fire_oem["Creation Date"].dt.year

oem_yearly = fire_oem.groupby("year").size().reset_index(name="oem_fire_incidents")
oem_yearly

/var/folders/_p/58k6zg2d0vqd17rj1r__6dxw0000gn/T/ipykernel_12885/3180665383.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/_p/58k6zg2d0vqd17rj1r__6dxw0000gn/T/ipykernel_12885/3180665383.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

    year  oem_fire_incidents
0   2011                  93
1   2012                 150
2   2013                 172
3   2014                 237
4   2015                 331
5   2016                 380
6   2017                 570
7   2018                 548
8   2019                 608
9   2020                 405
10  2021                 420
11  2022                 322

### Data cleaning for Fire Inspection

In [5]:

bfi_yearly = bfi.groupby("Case_Year").size().reset_index(name="bfi_confirmed_fires")

bfi_yearly = bfi_yearly.rename(columns={"Case_Year": "year"})
bfi_yearly

   year  bfi_confirmed_fires
0  2016                 7996
1  2017                 7350
2  2018                 6860
3  2019                 7064
4  2020                 6242
5  2021                 5494
6  2022                 5917
7  2023                 5683
8  2024                 5606
9  2025                 2623

### Merge by year

In [15]:
merged = pd.merge(oem_yearly, bfi_yearly, on="year")
merged

   year  oem_fire_incidents  bfi_confirmed_fires
0  2016                 380                 7996
1  2017                 570                 7350
2  2018                 548                 6860
3  2019                 608                 7064
4  2020                 405                 6242
5  2021                 420                 5494
6  2022                 322                 5917

### Data Visualization

In [21]:
import plotly.io as pio

pio.renderers.default = "notebook_connected+plotly_mimetype"
import plotly.express as px

fig = px.scatter(
    merged,
    x="oem_fire_incidents",
    y="bfi_confirmed_fires",
    text="year",
    labels={
        "oem_fire_incidents": "OEM Fire-Related Incidents",
        "bfi_confirmed_fires": "FDNY Confirmed Fire Investigations",
    },
    title="Relationship Between OEM Fire Incidents and FDNY Fire Investigations (2016–2024)",
    
)

fig.show()

## Explanation

The scatterplot shows no strong linear relationship between OEM fire-related emergency incidents and FDNY confirmed fire investigations from 2016 to 2024. Instead, the data forms two distinct clusters: a higher-activity period before COVID-19 (2017–2019) and a lower-activity period during the pandemic years (2020–2022). This suggests that both OEM and FDNY activity levels respond more to broad systemic shifts, such as changes in population movement and social activity—than to each other directly. The year 2016 appears as an outlier, likely reflecting operational or reporting differences. Overall, the lack of strong correlation aligns with the fact that OEM logs all fire-related calls, while FDNY BFI investigates only a subset of cases, resulting in diverging but somewhat parallel trends over time.